spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banner_category
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
